//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageId { get; set; }
        public string ImagePath { get; set; }
        public string UsernameFk { get; set; }
        public int Version { get; set; }
        public int DateCreated { get; set; }
    
        public virtual User User { get; set; }
    }
}
