//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogException
    {
        public int LogId { get; set; }
        public string ExceptionName { get; set; }
        public string ApplicationLevel { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
